version: "3"
services:
  notebook:
    container_name: datascience-notebook
    image: jupyter/datascience-notebook
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - ./work/:/home/jovyan
